<?php

// $Id$
/**
 * @file
 * Project Browser module.
 * Authored by Leighton Whiting for Google Summer of Code 2011
 * 
 * This module will provide a new UI for admins to easily browse modules and themes from their
 * admin pages, and install them.
 */

/**
 * Display help and module information
 */
function project_browser_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#project_browser":
      $output .= '<p>'.  t("Provides a UI for users to browse for and install new modules and themes from
      within their Drupal admin interface.") .'</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_perm().
 */
function project_browser_permission() {
  return array(
    'use project browser' => array(
      'title' => t('Use Project Browser'),
      'description' => t('This allows the user to browse for and install new modules and themes using Project Browser.'),
      'restrict access' => TRUE,
    )
  );
}

/**
 * Implementation of hook_menu().
 */
function project_browser_menu() {
  $items = array();
  $items['admin/settings/project_browser'] = array(
    'title' => 'Project Browser Settings',
    'description' => 'Set the various Project Browser Settings here',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('project_browser_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/project_browser/modules'] = array(
    'title' => 'Modules',
    'description' => 'Browse and search for new modules',
    'page callback' => 'project_browser_page',
    'page arguments' => array('module'),
    'access arguments' => array('use project browser'),
    'file' => 'project_browser.pages.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK
  );
  
  $items['admin/project_browser/themes'] = array(
    'title' => 'Themes',
    'description' => 'Browse and search for new themes',
    'page callback' => 'project_browser_page',
    'page arguments' => array('theme'),
    'access arguments' => array('use project browser'),
    'file' => 'project_browser.pages.inc',
    'type' => MENU_LOCAL_TASK
  );
  
  $items['admin/project_browser/install/%'] = array(
    'title' => 'Install',
    'page callback' => 'project_browser_installation_page',
    'page arguments' => array(2, 3),
    'access arguments' => array('use project browser'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'project_browser.pages.inc',
  );
  return $items;
}

// ======================================
// Administration Page:
// ======================================

/**
 * Admin Settings Form
 */
function project_browser_admin() {
  $form['main'] = array(
    '#type' => 'fieldset',
    '#title' => t('Main Settings'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    );
  $form['main']['project_browser_servers'] = array(
    '#type' => 'textarea',
    '#title' => t('Servers'),
    '#default_value' => variable_get('project_browser_servers', ''),
    '#description' => t("Add new servers to use for the Project Browser, one per line, in 
      the 'url|Server Name' format. Drupal.org is added by default, and doesn't need to be 
      set here."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

// ======================================
// Theme:
// ======================================

/**
 * Implements hook_theme() 
 */
function project_browser_theme() {
  return array(
    //Template for list of projects
    'project_browser_list' => array(
      'variables' => array('projects_list' => NULL),
      'file' => 'project_browser.pages.inc',
      'template' => 'project_browser_list',
    ),
    // Template for single project
    'project_browser_project' => array(
      'variables' => array('project' => NULL),
      'file' => 'project_browser.pages.inc',
      'template' => 'project_browser_project',
    ),
  );
}

/**
 * Implements hook_dashboard_regions()
 */
function project_browser_dashboard_regions() {
  return array('project_browser_sidebar_right' => 'Right sidebar for project browser page');
}